// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID           int    `json:"id"`
	User         *User  `json:"user"`
	Username     string `json:"username"`
	PasswordHash string `json:"passwordHash"`
}

type AuthOps struct {
	Login    *LoginResponse    `json:"login"`
	Register *RegisterResponse `json:"register"`
}

type GetUserInput struct {
	UserID int `json:"userId"`
}

type GetUserResponse struct {
	User *User `json:"user"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	UserID       int    `json:"userId"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	AccountID int    `json:"accountId"`
	UserID    int    `json:"userId"`
	Username  string `json:"username"`
	Message   string `json:"message"`
}

type User struct {
	ID            int     `json:"id"`
	LastName      string  `json:"lastName"`
	FirstName     string  `json:"firstName"`
	DateOfBirth   string  `json:"dateOfBirth"`
	Email         string  `json:"email"`
	PhoneNumber   string  `json:"phoneNumber"`
	Status        string  `json:"status"`
	AvatarImgPath *string `json:"avatarImgPath,omitempty"`
}
